### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by naymore** [mnadel/metrics.net.influxdb#10]
**This piece of code fails...**

```
    // METRICS.NET
    Metric.Config.WithReporting(report =>
          report.WithInflux(
               config.InfluxDbTargetDataRepositoryOptions.Host, // Uri
               config.InfluxDbTargetDataRepositoryOptions.UserName,
               config.InfluxDbTargetDataRepositoryOptions.Password,
               TimeSpan.FromSeconds(5)
     ));
```

**with the error message being:**

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Metrics.Reports.MetricsReports Metrics.Reports.MetricsReports.WithRep
ort(Metrics.Reporters.MetricsReport, System.TimeSpan)'.
   at Metrics.NET.InfluxDB.ConfigExtensions.WithInflux(MetricsReports reports, Uri influxdbUri, String username, String password, TimeSpan interval, ConfigOptions config)
```

Also I wonder how the InfluxDB measurement name is being set.
Can you set it yourself?

**Comment by mnadel** [comment]
What version of Metrics.NET and Metrics.NET.InfluxDB are you using?

What do you mean by measurement name? Have you looked at the `MetricNameConverter` facility?

**Comment by naymore** [comment]
I'm using the latest versions as of today.
InfluxDb has a concept of measurements, see [Key concepts](https://docs.influxdata.com/influxdb/v0.13/concepts/key_concepts/). It's basically a container where all your information goes to. For example I would like to have a measurement "projectX metrics".

Edit: I can look into that as I am working with InfluxDB (from time to time) - but I have no clue about Metrics.NET :-)

**Comment by mnadel** [comment]
Are you looking for a generic InfluxDB client for .NET?

**Comment by naymore** [comment]
No of course not. There are plenty of libraries for that :-)
**I'm looking for a working InfluxDB integration for Metrics.NET.**
If you on the other hand need a InfluxDB client for the Metrics.NET integration I'd go with [influxdb-csharp](https://github.com/influxdata/influxdb-csharp) - but use RX for the aggregation instead of the collector project.

**Comment by mnadel** [comment]
I don't think this lib supports your use case, sorry. Each metric is a separate measurement in the same InfluxDB database.

**Comment by naymore** [comment]
OK. Maybe I'll look into that :-)
