### ISSUE TITLE
Column naming

### ISSUE THREAD

**Issue by stephanstapel** [mnadel/metrics.net.influxdb#4]
Hi again,

Just one more thing I found in the code: you chose 'Value' and 'Count' as names for the value columns. As far as I understood, the standard for InfluxDB is 'value' which is used across the documentation and also in tools like Grafana.

How about using the standard naming scheme?

**Comment by mnadel** [comment]
So I understand, are you suggesting to replace Count and Value with lower-case value? Do you have a link to a document that discusses naming schemes?

I'm actually not a fan of the current naming scheme; all names currently need to be quoted. I'm thinking of collapsing names to remove spaces, dashes, etc, and make them dotted. Maybe using a regex similar to [StatD's](https://github.com/etsy/statsd/issues/110)?

**Comment by stephanstapel** [comment]
This page:

https://docs.influxdata.com/influxdb/v0.9/introduction/getting_started/

shows for example

´´´
INSERT cpu,host=serverA,region=us_west value=0.64
´´´

Concerning naming the metrics themselves I agree that the more or less automatic naming of Metrics.net is not optimal. Instead of "[MyApplication] MyMetric" I'd rather have something like myapplication.mymetric (other probably would use an underscore). This is why I'd like to know if Metrics.net project is still alive. I was considering offering a pull request. I'd opt for using String formatter like {0}.{1} (current default formatting would then be [{0}] - {1}) (Metrics.NET/Src/Metrics/MetricData/MetricsData.cs).

**Comment by mnadel** [comment]
Ah, sure, thanks. Will roll this fix and bump the minor version when released.

GitHub shows Eti's (the owner of Metric.NET) website as http://www.erata.net/. I sent an email to that domain's admin email address yesterday (which appears to be Eti's personal email address), but haven't heard back. We should probably start thinking about forking the project.

**Comment by mnadel** [comment]
Along these same lines, I'm thinking of modeling individual measurements as multi-valued events.

For example, consider a Meter. It has these values:

1. Total Count
1. Mean Rate
1. 1 Min Rate
1. 5 Min Rate
1. 15 Min Rate

Right now, I think each are a separate measurement/event.

I'm thinking it should be modeled more like this:

```
INSERT cpu,host=serverA,region=us_west count=0,mean=0,1m=0,5m=0,15m=0
```

Thoughts?

**Comment by stephanstapel** [comment]
I'd rather let this go into separate measurements. This would allow to set different retention policies to aggregate differently.
Also you can calculate these rates on your own with InfluxDB, so it'd be an option to wipe the rate measurements with a policy.

InfluxDB is a mixture between a pure time series database (timestamp/value/tags) and table based database (any field you desire) so there is probably no right and no wrong answer.

**Comment by stephanstapel** [comment]
Just digged through the documentation.

Page
https://docs.influxdata.com/influxdb/v0.9/concepts/schema_and_data_layout/

says that there should be one value field per series.

**Comment by mnadel** [comment]
Beautiful! Thanks for digging this up.

**Comment by mnadel** [comment]
I actually interpreted it slightly different. I think rates should be
additional columns of a particular measurement. I reached out to InfluxDB
for comment, as the "Schema Design" doc isn't all that thorough.

Agreed, however, on letting InfluxDB do the heavy lifting on calculating
the descriptive stats of a measurement.

I'll push to a new branch for review.

**Comment by mnadel** [comment]
Fixed in latest 2.x [prelease on NuGet](https://www.nuget.org/packages/Metrics.NET.InfluxDB/2.0.44-beta). Note that this is not backwards compatible w/ the 1.x series. See Changelog section of [README.md](https://github.com/mnadel/metrics.net.influxdb/blob/master/README.md).
