### ISSUE TITLE
Counter set values

### ISSUE THREAD

**Issue by marcinsikora** [mnadel/metrics.net.influxdb#5]
Hi,

I'm testing library with influxDB 0.9.4.2 (last Windows release).
I've noticed that the library doesn't save values for counter set items 
(as in example from https://github.com/etishor/Metrics.NET/wiki/Counters - Counting values from a set).

I think problem may lay in following lines in InfluxDbReport.cs:

```
var itemValues = value.Items.SelectMany(i => new [] { i.Count, i.Percent });
foreach (var data in new[] {(double) value.Count}.Concat(itemValues)) {
       Pack (name, columns, data, tags);
}
```
The foreach loop will call 
`private void Pack (string name, IEnumerable<string> columns, object value, MetricTags tags)`
method, which can add only one value for counter set.

I've changed counter reporting code for:
```
var itemValues = value.Items.SelectMany (i => new object[] { i.Count, i.Percent });
Pack(name, columns, (new[] { (object)value.Count }.Concat(itemValues)), tags);
```
to get set values saved in db. 
Are there any better ways to handle such case?

**Comment by mnadel** [comment]
Thanks, I see the issue now. I'm currently reworking how the data is
represented in Influx, and will address this with those changes.

**Comment by mnadel** [comment]
Fixed in latest 2.x [prelease on NuGet](https://www.nuget.org/packages/Metrics.NET.InfluxDB/2.0.44-beta). Note that this is not backwards compatible w/ the 1.x series. See Changelog section of [README.md](https://github.com/mnadel/metrics.net.influxdb/blob/master/README.md).
