### ISSUE TITLE
Derived Metrics in new version

### ISSUE THREAD

**Issue by mmarkzon** [mnadel/metrics.net.influxdb#6]
Thank you for this package.  I was wondering if you'd consider adding back the derived metrics and making it a configurable option to include them or not.  I see relying on the InfluxDB administrator to have to create Continuous Queries as not being very user friendly, when the users viewing the metrics (as in my case) are not going to be admins.  I would like my users to have the available metrics to them as needed, without having to contact an admin to generate a query.  I am not concerned if Continuous Queries are better performing.

Also could you please add license documentation to your repo?  For example, Metrics.NET has an Apache 2.0 license file.  Thanks!

**Comment by mnadel** [comment]
Makes sense. I'll add that as an option.

**Comment by mmarkzon** [comment]
Awesome, thanks!

**Comment by mmarkzon** [comment]
Will you be adding a license file to the repo, and if so do you know which one?

**Comment by mnadel** [comment]
I'll use the same as Metrics.NET itself.

**Comment by mmarkzon** [comment]
thank you!

**Comment by mnadel** [comment]
Derived metrics are pushed as part of 2.x (master branch, prerelease in NuGet).

**Comment by peske** [comment]
Me again, sorry for commenting on closed issues but it's only way for me to reach you with a question.

Well, I fully agree with @mmarkzon regarding this, and I'm glad that it is implemented. But one thing is not clear (and there's no documentation to check...). So the question is about your implementation: are derived metrics always pushed, or there is some configuration that need to be done (as mentioned in the original question)?

Btw. IMHO this library does not need to implement any similar advanced logic; instead it should be more like "data layer" which simply writes values from the source to db. If there are N values at the source - N values should be written in db. (It's my favourite "Keep It Short & Simple" strategy.)

Thanks again!

**Comment by mnadel** [comment]
Thanks for the feedback. Derived metrics are now always pushed; there's no way to turn them off. I'm currently planning on leaving it this way. If I understand this correctly - the reservoir sampling method employed by Metrics.NET means we lose the original fidelity, so we need to take its descriptive stats as the source of truth.

Agreed. This lib is just a lightweight transport layer. All it does is takes the stats, as-is, and formats them into a wire message that InfluxDB understands.
