### ISSUE TITLE
Upgrading to Polly 4.1.2

### ISSUE THREAD

**Issue by peske** [mnadel/metrics.net.influxdb#7]
First: thanks for this!

The second: problem :) Instead of referencing Polly 2.2.3 can you please migrate to Polly 4.1.2? The reason is simple - there's obviously a breaking change in Polly so your library does not work with the newest Polly. On the other side I would like to use the newest Polly for my other code...

Hope that it isn't too hard to do.

Thanks!

**Comment by mnadel** [comment]
Thanks -- I'm glad you find it useful! I actually pushed exactly this change this morning. It's available as 2.0.50-beta in NuGet.

**Comment by peske** [comment]
Thanks for really fast resolution! ;-)

**Comment by mnadel** [comment]
:)
